#!/bin/bash
  
export XKL_XMODMAP_DISABLE=1
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS

[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
xsetroot -solid grey

vncconfig -sconic &
gnome-panel &
gnome-settings-daemon &
metacity &

nonce="$(openssl rand -hex 4)"
nonce="${nonce^^}"

cd /home/ubuntu/Ti-Basic-BTC-Miner/source
sed -i "10 c \"$nonce\"->STR0" BTCINIT.tib
tibasic -o BTCINIT.8xp BTCINIT.tib

cemu -n -s BCHANGE.8xp \
  -s BTCDISP.8xp \
  -s BTCINIT.8xp \
  -s BTCMINE.8xp \
  -s CHOOSE.8xp \
  -s GAMMA0.8xp \
  -s GAMMA1.8xp \
  -s MAJORITY.8xp \
  -s ROTATE.8xp \
  -s SHACOMP.8xp \
  -s SHACONST.8xp \
  -s SHAPREP.8xp \
  -s SHAPREP2.8xp \
  -s SHAWLIST.8xp \
  -s SIGMA0.8xp \
  -s SIGMA1.8xp \
  --id abc &
sleep 30
cemu --id abc -u --launch BTCMINE
